"""admin not null

Revision ID: 221a711b73bd
Revises: de2f6b82add2
Create Date: 2023-02-22 16:25:29.304877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221a711b73bd'
down_revision = 'de2f6b82add2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Group', 'admin',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Group', 'admin',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
