"""cascade delete

Revision ID: 2b4a870f97e3
Revises: 4b7aef23f64e
Create Date: 2023-02-17 22:08:01.496164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4a870f97e3'
down_revision = '4b7aef23f64e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Message_group_id_fkey', 'Message', type_='foreignkey')
    op.create_foreign_key(None, 'Message', 'Group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.create_foreign_key('Message_group_id_fkey', 'Message', 'Group', ['group_id'], ['id'])
    # ### end Alembic commands ###
