"""username unique2

Revision ID: 4b7aef23f64e
Revises: 78c694660416
Create Date: 2023-02-17 17:34:17.606118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7aef23f64e'
down_revision = '78c694660416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User_username_key', 'User', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('User_username_key', 'User', ['username'])
    # ### end Alembic commands ###
