"""edited time in groups

Revision ID: 523e3ec3b3e1
Revises: 221a711b73bd
Create Date: 2023-02-25 16:41:31.201457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523e3ec3b3e1'
down_revision = '221a711b73bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Group', sa.Column('edited_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Group', 'edited_at')
    # ### end Alembic commands ###
