"""username unique2

Revision ID: 78c694660416
Revises: ded17fec10eb
Create Date: 2023-02-17 14:38:22.984358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c694660416'
down_revision = 'ded17fec10eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
