"""username

Revision ID: 86dd2096c712
Revises: 5c28c4966559
Create Date: 2023-02-17 13:48:03.204369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86dd2096c712'
down_revision = '5c28c4966559'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
