"""chch

Revision ID: de2f6b82add2
Revises: f2bf4d799afd
Create Date: 2023-02-19 01:44:25.697284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2f6b82add2'
down_revision = 'f2bf4d799afd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
