"""username unique2

Revision ID: ded17fec10eb
Revises: 6d59d9d0032f
Create Date: 2023-02-17 14:32:00.531309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded17fec10eb'
down_revision = '6d59d9d0032f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
